Add IBM scrapers
IBM-Cloud/infracost-cloud-pricing-api pull request #1
Opened 2022-06-28 17:23 UTC by hiltol

2022-06-28 17:45 UTC, balazs-marjan commented on src/scrapers/ibmCatalog.ts
> +type ResultsWithNext<Results extends Record<string, unknown> = Record<string, unknown>> = {
I think these opaque records make the code very hard to follow

2022-06-29 08:52 UTC, balazs-marjan commented on src/scrapers/ibmCatalog.ts
> +  writeFile(filename, JSON.stringify(results, null, 2));
these promises are not awaited

2022-06-29 08:52 UTC, balazs-marjan commented on src/scrapers/ibmCatalog.ts
> +  writeFile('products.json', JSON.stringify(products, null, 2));
these promises are not awaited

2022-06-29 09:03 UTC, balazs-marjan requested changes
I adjusted the PR to use my apikey for production, I would get an error otherwise. I got a lot of ECONNRESETS, I'm fairly certain the script is hitting ratelimits :thinking:
<img width="1680" alt="Screenshot 2022-06-29 at 11 03 13" src="https://user-images.githubusercontent.com/108288807/176397538-f6af118c-5f6e-4ea1-9c26-ed1e516812da.png">

2022-06-29 09:06 UTC, balazs-marjan commented on src/scrapers/ibmCatalog.ts
> +const client = GlobalCatalogV1.newInstance({});
It did for me

2022-06-29 09:50 UTC, balazs-marjan commented on src/scrapers/ibmCatalog.ts
> +    startQuantityTier: String(startQuantityTier),
I'm fairly certain this code tries to pull from the wrong place or just doesn't do anything
For every pasted product instance I get undefined values. i.e:
```
    "productHash": "b467373fa8e87482c57ccc27fcf68fbd",
    "sku": "datacatalog-professional",
    "vendorName": "ibm",
    "region": "eu-de",
    "service": "datacatalog",
    "productFamily": "service",
    "attributes": {
      "planName": "professional",
      "planType": "paygo",
      "startPrice": "undefined",
      "startQuantityTier": "undefined",
      "region": "eu-de"
    },
```

2022-06-29 15:54 UTC, balazs-marjan commented on package-lock.json
> +      "resolved": "https://na.artifactory.swg-devops.com/artifactory/api/npm/wcp-tmp-ace-fr-team-npm-virtual/expect/-/expect-26.6.2.tgz?dl=https%3A%2F%2Fregistry.npmjs.org%2Fexpect%2F-%2Fexpect-26.6.
I think internal artifactory might still be a problem

2022-06-29 17:08 UTC, balazs-marjan approved these changes

2022-07-05 12:12 UTC, balazs-marjan commented
Actually, how will we handle the conflicting records from the Kubernetes API and the GC entries?

2022-07-05 12:18 UTC, sonkatomi approved these changes

2022-07-07 07:50 UTC, merged